// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	models "github.com/edgexfoundry/edgex-go/internal/core/keeper/models"
	mock "github.com/stretchr/testify/mock"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// DeregisterByServiceId provides a mock function with given fields: id
func (_m *Registry) DeregisterByServiceId(id string) {
	_m.Called(id)
}

// Register provides a mock function with given fields: r
func (_m *Registry) Register(r models.Registration) {
	_m.Called(r)
}
